include:
    - docker/docker-mysql.yml

services:
    ospos:
        build: .
        restart: always
        depends_on:
            - mysql
        ports:
            - "${HOST_PORT:-8080}:80"
        networks:
            - app_net
        volumes:
            - uploads:/app/public/uploads
            - logs:/app/writable/logs
        environment:
            - CI_ENVIRONMENT=production
            - PHP_TIMEZONE=UTC
            - MYSQL_USERNAME=admin
            - MYSQL_PASSWORD=pointofsale
            - MYSQL_ROOT_PASSWORD=pointofsale
            - MYSQL_DB_NAME=ospos
            - MYSQL_HOST_NAME=mysql
